name: Trigger auto deployment for cccrawl

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cccrawl-AutoDeployTrigger-2c7db37a-347e-457b-84a0-ecf938050756.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.CCCRAWL_REGISTRY_USERNAME }}
          password: ${{ secrets.CCCRAWL_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: a10n/cccrawl:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CCCRAWL_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n cccrawl -g codecoach --server docker.io --username  ${{ secrets.CCCRAWL_REGISTRY_USERNAME }} --password ${{ secrets.CCCRAWL_REGISTRY_PASSWORD }}
            az containerapp update -n cccrawl -g codecoach --image a10n/cccrawl:${{ github.sha }}
